
Windows 10 RDP File
name CI


on [push, workflow_dispatch]


jobs

  build


    runs-on windows-latest


    steps

    - name Download

      run Invoke-WebRequest httpsbin.equinox.ioc4VmDzA7iaHbngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name Extract

      run Expand-Archive ngrok.zip

    - name Auth

      run .ngrokngrok.exe authtoken $EnvNGROK_AUTH_TOKEN

      env

        NGROK_AUTH_TOKEN ${{ secrets.NGROK_AUTH_TOKEN }}

    - name Enable TS

      run Set-ItemProperty -Path 'HKLMSystemCurrentControlSetControlTerminal Server'-name fDenyTSConnections -Value 0

    - run Enable-NetFirewallRule -DisplayGroup Remote Desktop

    - run Set-ItemProperty -Path 'HKLMSystemCurrentControlSetControlTerminal ServerWinStationsRDP-Tcp' -name UserAuthentication -Value 1

    - run Set-LocalUser -Name runneradmin -Password (ConvertTo-SecureString -AsPlainText P@ssw0rd! -Force)

    - name Create Tunnel

      run .ngrokngrok.exe tcp 3389





